### ISSUE TITLE
aws securityhub integration roadmap

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#3191]
# Overview

- [x] security hub cwe
- [x] finding filter
- [x] post-finding generic resource support
- [ ] policy to insight generation
- [x] docs
- [x] security hub cross-account actions

## Cross Account

For orgs that are using a centralized security hub across accounts, we should support post findings to the master account from members. The master/member relationship setup for securityhub is similiar to what's done for guard duty. It also would be good to add support to c7n-guardian for helping orgs setup on the multi-account setup.

## Finding filter -  #3309

Allow a custodian policy to use existing findings in a security hub as a filter for a custodian policy, for taking remediation actions on resources flagged by any finding provider.

## Security Hub CWE

Allow custodian policies to be used for real time incident response on a finding. Should also support being run in a centralized account. Note for security hub we'll also need to provision an action in the hub and reference that in our cwe subscription.

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cloudwatch-events.html

## PostFinding generic resource support

Security Hub atm only has specific resource support for ec2, container, s3, it does support a generic assignment to other, we should try to construct a generic resource assignment over to security hub for any resource custodian supports.

## Insight generation

Add a tool in ops, or perhaps as an option to post-finding action, to allow for creating insights automatically from a set of policies.

## Docs

Expand the post-finding action documentation with an example, separate documentation page to cover on narrative discussion.

**Comment by kapilt** [comment]
@FireballDWF ping, anything else come to mind that would be useful for custodian integration ?

**Comment by FireballDWF** [comment]
Cost Optimization via reusing FindingId and createdAt

**Comment by FireballDWF** [comment]
Re insights generation, the following is an awscli example to start with:
```
aws securityhub create-insight --name "Top Resources by count of findings from Cloud Custodian" --group-by-attribute "GeneratorId" --filters '{
            "RecordState": [
                {
                    "Value": "ACTIVE",
                    "Comparison": "EQUALS"
                }
            ],
            "ProductFields": [
                {
                    "Key": "ProviderName",
                    "Value": "CloudCustodian",
                    "Comparison": "CONTAINS"
                }
            ]
        }'
```

**Comment by kapilt** [comment]
i think we've hit parity on all security hub features, including some not mentioned here, lambda execution modes for custom actions and findings import processing w/ support for centralized cross account deployments. Also thanks to @FireballDWF we now have integration of custodian into the security hub partners program, https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-partner-providers.html

Our Reference Documentation for Security Hub -  https://cloudcustodian.io/docs/aws/topics/securityhub.html
