### ISSUE TITLE
tracking - Meet CNCF graduation criteria 

### ISSUE THREAD

**Issue by castrojo** [cloud-custodian/cloud-custodian#8132]
As  highlighted here: https://github.com/cncf/toc/blob/main/process/graduation_criteria.md

We need to meet the following criteria:

- [x] - Have committers from at least two organizations.
- [x] Have achieved and maintained a Core Infrastructure Initiative [Best Practices Badge](https://bestpractices.coreinfrastructure.org/).
- [ ] Have completed an independent and third party security audit
       - Submitted as [CNCFSD-1552](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1552)
- [ ] Explicitly define a [project governance and committer process](https://github.com/cloud-custodian/cloud-custodian/issues/7149). 
- [ ] Explicitly define the criteria, [process and offboarding or emeritus conditions](https://github.com/cloud-custodian/cloud-custodian/issues/7149) for project maintainers
- [x] Have a public list of project adopters for at least the primary repo (adopters.md)
- [ ] Receive a supermajority vote from the TOC to move to graduation stage.

The governance and emeritus policies are in draft, I'm taking an item to PR them officially over the next week or so.
